name: fx_wallet_packages

packages:
  - packages/**
  - examples/**

scripts:
  analyze:
    run: dart analyze .
    description: Run static analysis for all packages

  format:
    run: dart format .
    description: Format all Dart files

  test:
    run: flutter test
    description: Run all Flutter tests
