name: fx_wallet_packages

packages:
  - packages/**

scripts:
  analyze:
    run: melos exec -- "dart analyze"
    description: Run static analysis for all packages

  format:
    run: dart format .
    description: Format all Dart files

  test:
    run: melos exec -- "flutter test"
    description: Run all Flutter tests
