name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.3.4'

    - name: Install Melos
      run: dart pub global activate melos

    - name: Bootstrap
      run: melos bootstrap

    - name: Analyze
      run: melos run analyze

    - name: Format
      run: melos run format

    - name: Test
      run: melos run test